### ISSUE TITLE
Manpages generation (via ocamldoc) is broken - and tagging of ocamldoc targets is unpractical

### ISSUE THREAD

**Issue by Armael** [ocaml/ocamlbuild#10]
I'm opening this issue following https://github.com/gasche/manual-ocamlbuild/pull/25#issuecomment-166663474 . First, some facts:

- generation of manpages using ocamldoc is broken: trying to build a `api.docdir/man` target results in only a `api.docdir/man.stamp` file being generated;
- a workaround is to manually tag the target with tag `manpage`: the problem is ocamlbuild not tagging properly `api.docdir/man` as `manpage`.
- for other ocamldoc targets, the tagging is done by looking at the extension of the target. E.g., for html documentation, we have `flag ["ocaml"; "doc"; "docdir"; "extension:html"] (A"-html");;` at the end of `ocaml_specific.ml`. 

I'm willing to do a PR to correct the generation of manpages, however I'm not sure how to do this in a clean way (this is probably due to me not being familiar with ocamlbuild's codebase, though). One idea would be to write a wrapper to `Ocaml_tools.ocamldoc_l_dir`, that adds the `manpage` tag, and call it instead of `Ocaml_tools.ocamldoc_l_dir` in the corresponding rule in `ocaml_specific.ml`.

Maybe this is best kept for another issue, but I'm wondering if we could have a better system for tagging ocamldoc targets, instead of relying on the extension. For example, when using a custom ocamldoc generator (examples: [ocaml-libudev](https://github.com/Armael/ocaml-libudev/blob/master/myocamlbuild.ml#L40), [tyxml](https://github.com/ocsigen/tyxml/blob/master/myocamlbuild.ml#L57)), e.g. for html, one has to *not* pass the `-html` option to ocamldoc. The solution, which I find quite hackish, is then to write a wrapper that removes the `extension:html` tag, before calling `ocamldoc_l_dir`; and using it in a rule that overrides the standard one for `api.docdir/index.html` targets.

Thoughts?
— Armaël

**Comment by gasche** [comment]
I would just add some `~tags` parameter to `ocamldoc_l_{file,dir}`, as is done in other functions exposed by `Ocaml_compiler` (looking at `ocaml_specific.ml` only I see that for example `native_shared_library_link` has one). We may also be able to use this to stop relying on file extensions, by also adding it in other invocations of the rule to pass eg. a `htmldoc` flag instead of relying on `extension:html`. 

The ocamldoc rule with a `%(file)` pattern is a bit hackish right now and it may benefit from being split in specific rules for different kinds of builds. I think there is an interaction with my documentation work in ocaml/ocaml#231 (which I will try to send as a PR here soon-ish), as separate rules would be easier to document properly.

The fact that passing the `-html` option breaks custom generators may also be an ocamldoc issue: is this the right behavior, or should the tool be more resilient? I haven't thought about that so I don't know, but we should have a look at whether a clean fix on the ocamldoc side couldn't simplify things on ocamlbuild's end.

**Comment by Armael** [comment]
Ok. I submitted a PR with the minimal change to make manpages generation work ([here](https://github.com/ocaml/ocamlbuild/pull/21)). I'm now doing another one to, as you suggest, stop relying on file extensions and pass `htmldoc`, `texdoc`, etc. tags using this new [tags] parameter? I would thus split the `%(file)` rule into more specific rules.

As for ocamldoc custom generators, it may be indeed simpler to modify ocamldoc behavior so that the `-g foo.cmx` option overrides builtin generators, instead of the current behavior.

**Comment by gasche** [comment]
The manpage part of the bug has been solved by merging #21 (Armaël, you should use the PR number directly instead of putting a link, github will create a link and, more importantly, write a backreference in the PR itself; linking related issues together is very useful for future navigation).

Indeed I think that the good step forward is to split the too-general-for-its-own-good `%(file)` rule into target-specific rules.

Can you create an issue on the [compiler distribution bugtracker](http://caml.inria.fr/mantis/) for the ocamldoc thing? Of course a pull request would also be welcome there.

**Comment by Armael** [comment]
Submitted #35 .

**Comment by gasche** [comment]
Fixed by Armael in #35 and [MPR#7108](http://caml.inria.fr/mantis/view.php?id=7108).
