### ISSUE TITLE
Add namespaces to tags

### ISSUE THREAD

**Issue by tekknolagi** [ocaml/ocamlbuild#180]
Perhaps this is not the correct way to think about this. If so, please forgive me -- I am new to OCaml.

I am working on Reason, which provides a different syntax and toolchain around OCaml. We provide a wrapper around ocamlbuild called reasonbuild.

I added a new tag, `reason_add_printers`. That's all well and good but I think it would be better to add more explicit namespacing to tags so that Reason projects could tag as `reason.add_printers`, etc among the other OCaml tags or project-defined tags.

If there is a way to do this with pflags, what is the best way to go about it?

**Comment by gasche** [comment]
You can already use a dot in a tag name: nothing prevent you from calling your tag `reason.add_printers` as a discipline to clarify that this is a Reason-specific tag. There is no support for saying something like `open Reason` at the tags level, to let you write `add_printers` instead of the long version; but you can of course decide to always declare both the long and the short tag, so that if users detect a conflict they can decide to use the long version instead. Is that reasonable?

**Comment by tekknolagi** [comment]
Oh! That sounds great. Thank you.
