### ISSUE TITLE
License changed from ocaml days?

### ISSUE THREAD

**Issue by peterjc** [ocaml/ocamlbuild#275]
As of #8, a ``LICENSE`` file was added in f1d569fb2874c8359a371e4a3c8a2327d8421556 namely:

```
                  GNU LIBRARY GENERAL PUBLIC LICENSE
                       Version 2, June 1991
```

Using LGPL v2 is a change from when ``ocamlbuild`` was bundled as part of ``ocaml``, where as of v4.03 (the last release to include  ``ocamlbuild``) it was:

```
                   THE Q PUBLIC LICENSE version 1.0
```

http://caml.inria.fr/pub/distrib/ocaml-4.03/notes/LICENSE

Was this license change deliberate (and done with the permission of the copyright holders)?

Is the intent that LGPL v2 will apply to future releases, but the historic releases remain Q v1.0 only?

Or, are the historic releases now dual licensed under a choice of Q v1.0 or LGPL v2?

**Comment by peterjc** [comment]
Also, OCaml 4.04, 4.05 and 4.06 (current) are under LGPL v2.1, which is different again.

https://caml.inria.fr/pub/distrib/ocaml-4.04/notes/LICENSE
https://caml.inria.fr/pub/distrib/ocaml-4.05/notes/LICENSE
https://caml.inria.fr/pub/distrib/ocaml-4.06/notes/LICENSE

See also https://github.com/ocaml/ocaml/commit/7fc2d214c4ee8853615fc3e5649f45e11d85378d

**Comment by whitequark** [comment]
Using LGPLv2 (not v2.1) is clearly wrong.

**Comment by gasche** [comment]
The license was changed shortly before ocamlbuild was split from the compiler distribution, in https://github.com/ocaml/ocaml/commit/688d5a5915172c0b0f259c298e1676da51b2fa13, by Xavier Leroy who I believe acts as the copyright holder here. (Technically I believe that there was a unique copyright holder, INRIA, which delegates these matters to Xavier (one of INRIA's employees).)

The choice of using LGPL+linking exception rather than the QPL was done with the intent of using a better license for ocamlbuild to live its own life unburdened by license concerns. The particular flavor of LGPL was the one already used by some parts of the compiler distribution (such as the compiler library), namely LGLv2 (not v2.1).

I believe that we could change ocamlbuild's license to LGPLv2.1 if there was a desire to do so. (We haven't had people sign copyright delegation forms since ocamlbuild was split, so it would require to ask contributors, but this isn't too hard in the github days.)
On the other hand, I am not convinced that there is a very strong need to do it, given that LGPLv2 is okay-ish, and that I don't expect ocamlbuild's development to be very active in the future, given that the general community seems to have moved towards using and contributing to jbuilder/dune instead.

**Comment by peterjc** [comment]
OK - so it was deliberate and not a mistake that ``ocaml`` and ``ocamlbuild`` now have different licenses.

I can see advantages to moving to "LGPL v2.0 or later" as maximising potential reuse of the code, but also understand that if you don't have a contributors copyright transfer agreement getting everyone's permission to change the license now would be a pain.
