### ISSUE TITLE
OCAMLLIB overrides `ocamlbuild -where`, which is no longer correct in OPAM environment

### ISSUE THREAD

**Issue by camlspotter** [ocaml/ocamlbuild#69]
Now OCamlBuild can be installed by OPAM and its library directory, typically `$HOME/.opam/<switch>/lib/ocamlbuild` is different from `$OCAMLLIB/ocamlbuild` when the "system" compiler is used.  However, `ocamlbuild_where.ml` still checks the variable and override the lib dir when it is defined.

**Comment by camlspotter** [comment]
OASIS also assumes ocamlbuild library directory is `ocamlc -where`/ocamlbuild. See: https://forge.ocamlcore.org/tracker/index.php?func=detail&aid=1538&group_id=54&atid=291

**Comment by camlspotter** [comment]
A workaround is not to use "system" compiler, but it is hard to switch in Cygwin OPAM + MinGW OCaml environment. (I think...)

**Comment by gasche** [comment]
Should we just remove the lookup to OCAMLLIB, or maybe replace it by OCAMLBUILD_LIBDIR, which is the variable name we use at configuration time?

**Comment by whitequark** [comment]
> Should we just remove the lookup to OCAMLLIB, or maybe replace it by OCAMLBUILD_LIBDIR, which is the variable name we use at configuration time?

Context: https://caml.inria.fr/mantis/view.php?id=4379. Do you think it should be removed? In my opinion, since the advent of package managers, it is very rare to want to use an ocamlbuild with an compiler other than the one it was built with, and such cases are sufficiently accomodated with -install-lib-dir, so I think it should be just removed and not replace with another environment variable.

In any case, the current behavior is incorrect.

**Comment by whitequark** [comment]
On reflection, my reasoning is incorrect. Anyone trying to distribute binary builds of ocamlbuild (for Windows or elsewhere) will encounter this problem. But the environment variable solution is still quite bad, as it is not easy to diagnose and results in pollution of environment.

I wonder how ocamlfind copes with this?

**Comment by dra27** [comment]
Just been bitten by this - ocamlbuild reading OCAMLLIB is not what caused me problems, it's the fact that it's not taken into account that it was installed using findlib (so it's `$OCAMLLIB/site-lib/ocamlbuild`). Even if you want the pain of trying to distribute binary builds for Windows, it would seem to be a good idea for ocamlbuild to fix the `/ocamllib` suffix at configure-time based on how ocamlbuild is configured to be installed.

**Comment by gasche** [comment]
I'm bad at thinking about (and fixing) these kind of things, and don't have Windows testing environment. But I would welcome any reasonable and tested patch that solves the problem for Windows users.

**Comment by dra27** [comment]
This isn't so much a matter of Windows-testing - it's just that setting OCAMLLIB is more common on Windows, because of using binary installation. That'll be becoming less the norm with opam taking over installations, though.

I would strongly countenance against introducing a new environment variable (I agree with @whitequark that it's a bad solution in general, and I certainly don't think having to worry about two different environment variables would help fix this). I would suggest that the solution should get as close to the 3.11.1-4.02.3 solution where this basically "just worked" (not that, as a Windows user, I have ever regarded ocamlbuild as "just working" :wink:).

I wonder if the simplest thing is to break installations into two categories:
1. `ocamlbuild` is a subdirectory of OCaml's own libdir. Prior to 4.03.0, this was always the case so just `$OCAMLLIB/ocamlbuild`. For 4.03.0+, this would now also include default findlib installations where it's in the `site-lib` subdirectory of OCaml's libdir.
2. `ocamlbuild` is installed in a place which is not a subdirectory of OCaml's libdir (e.g. opam)

If you've built ocamlbuild to be used in the second kind of set-up (either via opam, or via an OS package manager which puts site-lib in a totally separate place) then I'm not clear why you would ever want to be using `OCAMLLIB` at all - indeed, with some of the new setenv power added in opam 2.0, it's conceivable that `opam config env` may start clearing `OCAMLLIB` at some point (especially managing system compilers on Windows). So for the second case, I would say that `ocamlbuild -where` should *ignore* the value of `OCAMLLIB`. For the first case, I think instead of appending `/ocamlbuild`, `ocamlbuild -where` should append the difference between `OCAML_LIBDIR` and `OCAMLBUILD_LIBDIR` - so for most findlib installations, that would then append `/site-lib/ocamlbuild` instead.

I'm quite happy to code that - it's a few (ab)uses of `$(abspath ...)` here and there and a couple of extra internal config fields. What do you think?

(FWIW, I've actually hit this working on Linux, but don't tell anybody.....)

**Comment by gasche** [comment]
Whatever you and @whitequark can agree with is completely fine with me.

**Comment by gasche** [comment]
#240 implement the idea, but I myself have no opinion. @whitequark, @dbuenzli, @camlspotter, do you agree with the proposal?

**Comment by whitequark** [comment]
@dra27 Does this actually handle relocatable ocamlbuild binaries? If yes I do not fully understand how.

**Comment by dra27** [comment]
@whitequark - no, I don't think it does (you mean having an ocamlbuild binary which you can install anywhere?). That's neither my aim nor interest here, at least at the moment.

It's been very common on native Windows (or at least it was when I started using it in 2003) to set `OCAMLLIB` and expect everything to adapt. For this reason, ocamlbuild was altered in 3.11.1 to use `OCAMLLIB` and, because it was part of the compiler, it simply made an assumption about where ocamlbuild should be relative to `OCAMLLIB`. All I'm "fixing" here is something which was missed when ocamlbuild was put out to pasture in 4.03.0.

**Comment by whitequark** [comment]
I don't fully understand every consequence of this change, but I don't see anything obviously wrong with it, and don't presently have time to think about it in-depth, so LGTM.

**Comment by gasche** [comment]
I agree with the LGTM reasoning, so I merged. I am going to optimistically close the issue, assuming that the change fixed it. If you get hit again, please complain here and I'll reopen.
