### ISSUE TITLE
source files starting with underscore are ignored

### ISSUE THREAD

**Issue by agarwal** [ocaml/ocamlbuild#96]
```
$ touch a _b

$ ocamlbuild a
Finished, 0 targets (0 cached) in 00:00:00.

$ ocamlbuild _b
Solver failed:
  Ocamlbuild knows of no rules that apply to a target named _b. This can happen if you ask Ocamlbuild to build a target with the wrong extension (e.g. .opt instead of .native) or if the source files live in directories that have not been specified as include directories.
Compilation unsuccessful after building 0 targets (0 cached) in 00:00:00.
```

Is there a workaround?

**Comment by dbuenzli** [comment]
This should have been solved by https://github.com/ocaml/ocamlbuild/pull/50

**Comment by gasche** [comment]
Indeed, it works with 0.9.1 and later versions.

**Comment by agarwal** [comment]
Thanks. My search didn't lead to that pull request. Unfortunately it requires me moving to OCaml >= 4.03, which I can't do yet.

**Comment by gasche** [comment]
Thanks for the report in any case; I'm glad to know that someone else than Daniel has a use for this feature (which has caused us some small trouble because of unintended consequences with alternate `_build_foo` directories).

**Comment by gasche** [comment]
One thing you could do to solve the `>= 4.03` issue is to setup a switch of OCaml 4.02.3 compiled without ocamlbuild (using the `-no-ocamlbuild` option at compiler-configuration time) and without the `base-ocamlbuild` base package (of course). You should be able to install separate-ocamlbuild there -- although the current opam files do require ">= 4.03" for safety reasons, so you might have to pin or otherwise override that metadata.

**Comment by agarwal** [comment]
Thanks for the proposal, but no need for the extra work. I wrote a rule to copy files starting with an underscore, a perfectly easy workaround.

FYI, my real use case relates to CSS styles. I use `sass` to compile `scss` files to `css`. It is common convention to start scss filenames with an underscore when their only point is to be included in another scss file.
